# Generated by Django 5.0.2 on 2024-02-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_product_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app1.subcategory'),
            preserve_default=False,
        ),
    ]
