# Generated by Django 5.0.2 on 2024-02-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(related_name='categories', to='app1.subcategory'),
        ),
    ]
