# Generated by Django 5.0.2 on 2024-02-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
