# Generated by Django 5.0.2 on 2024-02-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_remove_product_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app1.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
