# Generated by Django 5.0.2 on 2024-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_category_parent_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
